### ISSUE TITLE
[Suggestion] Option to sort sidebar by profitability

### ISSUE THREAD

**Issue by keoShine** [LucasPickering/runelite-herb-farm-calculator#3]
It'd be hella rad to have an option to sort the sidebar by profitability rather than just herb level.. It can sometimes be a bit of a strain to compare numbers quickly to see which herb is most profitable on a given day when they're not in a great order to do that comparison, so sorting by profit would help a lot to be able to see at a glance what's most worth planting..

**Comment by LucasPickering** [comment]
@keoShine Sorry for the slow response. I like this idea but I'm pretty busy working on other projects right now. I'd be happy to review a PR for this, otherwise it'll probably be a few weeks at least until I can get to it.
